# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  ##port: 8091
  port: 8091
  servlet:
    # 应用的访问路径
    context-path: /
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.recruitment.chat: DEBUG
    org.springframework: INFO

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
# MyBatis配置
#mybatis:
#    # 搜索指定包别名 需加载MyBatisConfig.java
#    typeAliasesPackage: com.xydl.web.**.domain
#    # 配置mapper的扫描，找到所有的mapper.xml映射文件
#    mapperLocations: classpath*:mapper/**/*Mapper.xml
#    # 加载全局的配置文件
#    configLocation: classpath:mybatis/mybatis-config.xml


